import { ETO }  from '../../Class/ETO';
import { Speed }  from '../../Class/Speed';
import { Sowing }  from '../../Class/Sowing';
import { Moisture }  from '../../Class/Moisture';

export const ListRuleDefault = [
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 5),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 5),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 5),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 5),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 4),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 1),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 3),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 2),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 1),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 2),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 2),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 3),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 1),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 2),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 3),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 4),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },
    {
        eto: new ETO(0, 5),
        moisture: new Moisture(0, 3),
        sowing: new Sowing(0, 4),
        speed: new Speed(0, 1),
    },

]
